FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM tomcat:10.1-jdk17
RUN rm -rf $CATALINA_HOME/webapps/ROOT
COPY --from=build /app/target/calculator.war $CATALINA_HOME/webapps/ROOT.war
EXPOSE 8080
